# Mapping of ISO Alpha-2 codes to Polish capital names
CAPITAL_MAPPING_PL = {
    'AF': 'Kabul', 'AL': 'Tirana', 'DZ': 'Algier', 'AD': 'Andora', 'AO': 'Luanda', 
    'AG': "Saint John's", 'AR': 'Buenos Aires', 'AM': 'Erywań', 'AU': 'Canberra', 'AT': 'Wiedeń', 
    'AZ': 'Baku', 'BS': 'Nassau', 'BH': 'Manama', 'BD': 'Daka', 'BB': 'Bridgetown', 
    'BY': 'Mińsk', 'BE': 'Bruksela', 'BZ': 'Belmopan', 'BJ': 'Porto-Novo', 'BT': 'Thimphu', 
    'BO': 'Sucre', 'BA': 'Sarajewo', 'BW': 'Gaborone', 'BR': 'Brasília', 'BN': 'Bandar Seri Begawan', 
    'BG': 'Sofia', 'BF': 'Wagadugu', 'BI': 'Gitega', 'KH': 'Phnom Penh', 'CM': 'Jaunde', 
    'CA': 'Ottawa', 'CV': 'Praia', 'CF': 'Bangui', 'TD': 'Ndżamena', 'CL': 'Santiago', 
    'CN': 'Pekin', 'CO': 'Bogota', 'KM': 'Moroni', 'CG': 'Brazzaville', 'CD': 'Kinszasa', 
    'CR': 'San José', 'CI': 'Jamusupro', 'HR': 'Zagrzeb', 'CU': 'Hawana', 'CY': 'Nikozja', 
    'CZ': 'Praga', 'DK': 'Kopenhaga', 'DJ': 'Dżibuti', 'DM': 'Roseau', 'DO': 'Santo Domingo', 
    'EC': 'Quito', 'EG': 'Kair', 'SV': 'San Salvador', 'GQ': 'Malabo', 'ER': 'Asmara', 
    'EE': 'Tallinn', 'ET': 'Addis Abeba', 'FJ': 'Suva', 'FI': 'Helsinki', 'FR': 'Paryż', 
    'GA': 'Libreville', 'GM': 'Bandżul', 'GE': 'Tbilisi', 'DE': 'Berlin', 'GH': 'Akra', 
    'GR': 'Ateny', 'GD': "Saint George's", 'GT': 'Gwatemala', 'GN': 'Konakry', 'GW': 'Bissau', 
    'GY': 'Georgetown', 'HT': 'Port-au-Prince', 'HN': 'Tegucigalpa', 'HU': 'Budapeszt', 'IS': 'Reykjavík', 
    'IN': 'Nowe Delhi', 'ID': 'Dżakarta', 'IR': 'Teheran', 'IQ': 'Bagdad', 'IE': 'Dublin', 
    'IL': 'Jerozolima', 'IT': 'Rzym', 'JM': 'Kingston', 'JP': 'Tokio', 'JO': 'Amman', 
    'KZ': 'Astana', 'KE': 'Nairobi', 'KI': 'South Tarawa', 'KP': 'Pjongjang', 'KR': 'Seul', 
    'KW': 'Kuwejt', 'KG': 'Biszkek', 'LA': 'Wientian', 'LV': 'Ryga', 'LB': 'Bejrut', 
    'LS': 'Maseru', 'LR': 'Monrovia', 'LY': 'Trypolis', 'LI': 'Vaduz', 'LT': 'Wilno', 
    'LU': 'Luksemburg', 'MG': 'Antananarywa', 'MW': 'Lilongwe', 'MY': 'Kuala Lumpur', 'MV': 'Male', 
    'ML': 'Bamako', 'MT': 'Valletta', 'MH': 'Majuro', 'MR': 'Nuakszut', 'MU': 'Port Louis', 
    'MX': 'Meksyk', 'FM': 'Palikir', 'MD': 'Kiszyniów', 'MC': 'Monako', 'MN': 'Ułan Bator', 
    'ME': 'Podgorica', 'MA': 'Rabat', 'MZ': 'Maputo', 'MM': 'Naypyidaw', 'NA': 'Windhuk', 
    'NR': 'Yaren', 'NP': 'Katmandu', 'NL': 'Amsterdam', 'NZ': 'Wellington', 'NI': 'Managua', 
    'NE': 'Niamey', 'NG': 'Abudża', 'MK': 'Skopje', 'NO': 'Oslo', 'OM': 'Maskat', 
    'PK': 'Islamabad', 'PW': 'Ngerulmud', 'PA': 'Panama', 'PG': 'Port Moresby', 'PY': 'Asunción', 
    'PE': 'Lima', 'PH': 'Manila', 'PL': 'Warszawa', 'PT': 'Lizbona', 'QA': 'Doha', 
    'RO': 'Bukareszt', 'RU': 'Moskwa', 'RW': 'Kigali', 'KN': 'Basseterre', 'LC': 'Castries', 
    'VC': 'Kingstown', 'WS': 'Apia', 'SM': 'San Marino', 'ST': 'Sao Tome', 'SA': 'Rijad', 
    'SN': 'Dakar', 'RS': 'Belgrad', 'SC': 'Victoria', 'SL': 'Freetown', 'SG': 'Singapur', 
    'SK': 'Bratysława', 'SI': 'Lublana', 'SB': 'Honiara', 'SO': 'Mogadiszu', 'ZA': 'Pretoria', 
    'SS': 'Dżuba', 'ES': 'Madryt', 'LK': 'Sri Dźajawardanapura Kotte', 'SD': 'Chartum', 'SR': 'Paramaribo', 
    'SZ': 'Mbabane', 'SE': 'Sztokholm', 'CH': 'Berno', 'SY': 'Damaszek', 'TJ': 'Duszanbe', 
    'TZ': 'Dodoma', 'TH': 'Bangkok', 'TL': 'Dili', 'TG': 'Lome', 'TO': 'Nukuʻalofa', 
    'TT': 'Port-of-Spain', 'TN': 'Tunis', 'TR': 'Ankara', 'TM': 'Aszchabad', 'TV': 'Funafuti', 
    'UG': 'Kampala', 'UA': 'Kijów', 'AE': 'Abu Zabi', 'GB': 'Londyn', 'US': 'Waszyngton', 
    'UY': 'Montevideo', 'UZ': 'Taszkent', 'VU': 'Port Vila', 'VA': 'Watykan', 'VE': 'Caracas', 
    'VN': 'Hanoi', 'YE': 'Sana', 'ZM': 'Lusaka', 'ZW': 'Harare'
}
